dist: trusty
language: perl
perl:
- '5.22'    # because there's no 5.22.2 :(
- '5.20.3'
- '5.18.2'  # because it's all that seems to be available
before_install:
- git clone git://github.com/haarg/perl-travis-helper
- source perl-travis-helper/init
- build-perl
- perl -V
- cpan-install Dist::Zilla~6.008
- git config --global user.email "travis.ci@chizography.net"
- git config --global user.name "Travis CI"
- build-dist
- cd $BUILD_DIR
install:
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c
  HARNESS_TIMER=1
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest --installdeps .
script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove
  -lrsv t
- cover
after_success:
- cover -report coveralls
notifications:
  slack:
    secure: cGyeQuIuoqeeuSe3yslXhHu07xR8ZZdiC/Ahc42Tj1Gg2vwDTXLEH2LahzVYu7/nTpCL13Q8qAdE6VZ7+3HIg5zKb75HF0bOS0I+Ycyiy9YeVwl6b6bk0PD3/IdLd3gW/MhGn0m9ysYIq/MnpbSTLs5ZwFK9B6m6s2YCOgMAYbuOuDxhmf/Qm1KZiugZ6SF7gjMwVmXt2Gq7qo+DWjHukWjjthWNqQID/waXkpvtV0845uGipHr0kinfaMWXrvjKsrwt7NKZRVqEqmRVQheVUSV+67yDTOcnrwyJsTRtvdNbCi2Mpk19Sz8w7WvVInfAD3n0oYPMXv2Q/08Gw8Qmm4htkrWjMEHXcxgeO1Br0ux47BZOVUGhjkUMfLHFdZqa3u8jz4xjvZjmVHeL6/Rq/2QWrYVfV26mEYGAONs4S03KT4div9ujjc2eBSxJwxpwgaO+3PPXWGf6ZoOsIe4InYiWzrqGarodMgvchb/H00PJxbkp4TgGP8TRPN7Oj1mpzwF6g6dj8FqeG1I+MqdfVLXzT0J1M51NJPfOmAa7BBADOamIP9n/loWTk0ajNuI1sBEL7Ly2o9JRL7lmyI6PSpVwQ7kNcjmzl8GYPkIyakEkzB38aL6Uvik4s3DTk32m2WcIk3VohWCNlf3UwrMC3oRoEFLgUgqDXnKgD3FUXOs=
matrix:
  allow_failures:
    - '5.22'
    - '5.20.3'
    - '5.18.2'
